BoxChampionship/Controllers/BattlesController.cs
using BoxChampionship.Services;
using BoxChampionship.ViewModels;
using System.Web.Mvc;

namespace BoxChampionship.Controllers
{
    public class BattlesController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(new BattlesAdd());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(BattlesAdd vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            else if (vm.Boxer1_Score == vm.Boxer2_Score)
            {
                TempData["PointsErrorMessage"] = "The count of points cant be same";
                return View(vm);
                
            }
            else
            {

                Services.TryCreateBattle.CreatingBattle(vm);
                TempData["SuccessMessage"] = "The battle was successfully added!";
                return RedirectToAction("Index");
            }
        }
           
    }
}

BoxChampionship/Controllers/ChampionshipController.cs
using BoxChampionship.Models;
using BoxChampionship.Services;
using BoxChampionship.ViewModels; 
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.Linq;

using System.Web.Mvc;
using System.Web.Services.Description;
using System.Web.UI;

namespace BoxChampionship.Controllers
{
    public class ChampionshipController : Controller
    {

        public ActionResult Index()
        {
           var vm= ChampionshipMetods.GetContainer();
            return View(vm);
        }

        public JsonResult GetData(string sidx, string sord, int page, int rows, int championshipId, string boxerFilter)
        {
            object dataFromService = Services.ChampionshipMetods.GetRankingsData(sidx, sord, page, rows, championshipId, boxerFilter);
            return Json(dataFromService, JsonRequestBehavior.AllowGet);
        }



    }
}

BoxChampionship/Controllers/MainController.cs
using BoxChampionship.Services;
using Microsoft.Build.Framework;
using System.Diagnostics;
using System.Web.Mvc;

namespace BoxChampionship.Controllers
{
    public class BattlesListViewController : Controller
    {


        public ActionResult Index()
        {
            var vm = BattlesMetods.GetContainer();
            return View(vm);
        }

        public JsonResult GetData(string sidx, string sord, int page, int rows, string winLossFilter, string boxerNameFilter)
        {
            object dataFromService = Services.BattlesMetods.GetRankingsData(sidx, sord, page, rows, winLossFilter, boxerNameFilter);
            return Json(dataFromService, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetBattleDetails(int id)
        {
            var battleDetails = Services.BattlesMetods.GetSingleBattleDetails(id);
            return Json(battleDetails, JsonRequestBehavior.AllowGet);
        }

    }
}

BoxChampionship/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Box Championship</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/jqueryui")
    @Styles.Render("~/Content/jqgrid")

</head>
<body>
    <header>
        <span class="logo">Box Championship</span>
        <nav>
            <a href="@Url.Action("Index", "BattlesListView")">BattlesListView</a>
            <a href="@Url.Action("Index", "Battles")">BattlesAdd</a>
          
            <a href="@Url.Action("Index", "Championship")">Championships</a>
        </nav>
    </header>

    <main>
        @RenderBody()
    </main>

    <footer>
        <span></span>
    </footer>

    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqgrid")

   
    @RenderSection("Scripts", required: false)

</body>
</html>